title: Hello, world! I'm Keshan Sodimana
description: > # this means to ignore newlines until "baseurl:"
  This is my personal website and blog. I will write about Machine Learning, Artificial Intelligence, Mathematics and Science in this blog.
permalink: ":title/"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Keshan Sanjaya Sodimana # add your name
author-img: keshan.jpg # add your photo
about-author: I am a Machine Learning enthusiast with a Computer Science background. Enjoy travelling, reading and learning cool new stuff. # add description
social-twitter: crazykesh # add your Twitter handle
social-facebook:
social-huggingface: keshan
social-github: keshan # add your Github handle
social-linkedin: keshan # add your Linkedin handle
social-email: keshan88@gmail.com # add your Email address

# Disqus
discus-identifier: keshan # add your discus identifier

# Tracker
analytics: UA-122765133-1 # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
  - jekyll-minifier
paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
